apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SwissTmsNetworkPolicyRequired
metadata:
  name: networkpolicy-required-swisstms
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - swisstms-zh
      - swisstms-ld4
      - swisstms-ny4
      - swisstms-ty3
      - swisstms-uat
