image:
  repository: ghcr.io/tobiasoberrauch/swisstms-reporting-service
  tag: 0.1.0
replicaCount: 1
service: { port: 8083 }
env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swisstms
resources:
  requests: { cpu: 200m, memory: 512Mi }
  limits:   { cpu: 1000m, memory: 2Gi }
