#!/usr/bin/env bash
#
# T106 — Scaffolds a new venue adapter.
#
#   make new-venue NAME=cboe
#   ./scripts/new-venue.sh cboe
#
# Generates:
#   apps/venue-adapter-<name>/build.gradle.kts
#   apps/venue-adapter-<name>/src/main/java/ch/swisstms/venue/<name>/<Name>VenueAdapter.java
#   apps/venue-adapter-<name>/src/main/resources/application.yml
#   apps/venue-adapter-<name>/src/test/java/ch/swisstms/venue/<name>/<Name>BasicLifecycleTest.java
#   docs/decisions/0xxx-venue-adapter-<name>.md  (numbered next available)
# and updates settings.gradle.kts.

set -euo pipefail

NAME="${1:-${NAME:-}}"
if [[ -z "${NAME}" ]]; then
  echo "Usage: $0 <name>   or   make new-venue NAME=<name>"
  exit 1
fi

LOWER="$(echo "${NAME}" | tr '[:upper:]' '[:lower:]')"
PASCAL="$(echo "${LOWER:0:1}" | tr '[:lower:]' '[:upper:]')${LOWER:1}"
DIR="apps/venue-adapter-${LOWER}"

if [[ -d "${DIR}" ]]; then
  echo "✗ ${DIR} already exists"
  exit 1
fi

echo "→ Scaffolding ${DIR} (class ${PASCAL}VenueAdapter)…"

mkdir -p "${DIR}/src/main/java/ch/swisstms/venue/${LOWER}"
mkdir -p "${DIR}/src/main/resources"
mkdir -p "${DIR}/src/test/java/ch/swisstms/venue/${LOWER}"
mkdir -p "${DIR}/helm"

cat > "${DIR}/build.gradle.kts" <<EOF
plugins {
    \`java-library\`
    id("org.springframework.boot") version "3.3.4"
    id("io.spring.dependency-management") version "1.1.6"
}

description = "Swiss-TMS — ${PASCAL} venue adapter."

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation(project(":libs:domain-model"))
    implementation(project(":libs:time-sync"))
    implementation(project(":libs:observability"))

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("net.jqwik:jqwik:1.9.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.0")
}
EOF

cat > "${DIR}/src/main/java/ch/swisstms/venue/${LOWER}/${PASCAL}VenueAdapter.java" <<EOF
package ch.swisstms.venue.${LOWER};

import ch.swisstms.domain.execution.ExecutionReport;
import ch.swisstms.domain.health.HealthSnapshot;
import ch.swisstms.domain.health.LatencyTier;
import ch.swisstms.domain.marketdata.MarketDataTick;
import ch.swisstms.domain.marketdata.SubscriptionRequest;
import ch.swisstms.domain.order.CancelRequest;
import ch.swisstms.domain.order.Order;
import ch.swisstms.domain.order.OrderAck;
import ch.swisstms.domain.order.ReplaceRequest;
import ch.swisstms.domain.ports.VenueGatewayPort;
import ch.swisstms.time_sync.RegulatoryClock;

import org.springframework.stereotype.Component;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.Flow;
import java.util.concurrent.SubmissionPublisher;

/**
 * Generated by scripts/new-venue.sh — implements {@link VenueGatewayPort}
 * for ${PASCAL}.
 *
 * <p>Constitution Principle I — adding a new venue means adding a new
 * adapter alone. The OMS, EMS, reconciler, reporting and surveillance
 * services pick this up automatically via Spring DI (SpringVenueRouter).
 *
 * <p>TODO: replace TODOs below with the venue's protocol implementation.
 */
@Component
public class ${PASCAL}VenueAdapter implements VenueGatewayPort {

    private static final String VENUE_MIC = "TODO"; // 4-char MIC

    private final SubmissionPublisher<ExecutionReport> executions = new SubmissionPublisher<>();
    private final SubmissionPublisher<MarketDataTick> marketData = new SubmissionPublisher<>();

    @Override
    public CompletionStage<OrderAck> submitOrder(Order order) {
        // TODO: translate Order → venue protocol; await ack
        throw new UnsupportedOperationException("submitOrder not yet implemented");
    }

    @Override public CompletionStage<Void> cancelOrder(CancelRequest req) {
        throw new UnsupportedOperationException();
    }
    @Override public CompletionStage<Void> replaceOrder(ReplaceRequest req) {
        throw new UnsupportedOperationException();
    }
    @Override public Flow.Publisher<ExecutionReport> executions() { return executions; }
    @Override public Flow.Publisher<MarketDataTick> marketData(SubscriptionRequest req) { return marketData; }
    @Override public HealthSnapshot health() {
        return new HealthSnapshot(VENUE_MIC, HealthSnapshot.Status.DISCONNECTED,
            RegulatoryClock.nowBiz(), 0L, 0L, "skeleton — see ADR");
    }
    @Override public String venueMic() { return VENUE_MIC; }
    @Override public LatencyTier tier() { return LatencyTier.WARM; }
}
EOF

cat > "${DIR}/src/main/resources/application.yml" <<EOF
spring:
  application:
    name: venue-adapter-${LOWER}
server:
  port: 81??     # TODO: pick a free port
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
EOF

cat > "${DIR}/src/test/java/ch/swisstms/venue/${LOWER}/${PASCAL}BasicLifecycleTest.java" <<EOF
package ch.swisstms.venue.${LOWER};

import ch.swisstms.domain.health.HealthSnapshot;
import ch.swisstms.domain.health.LatencyTier;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/** TODO: implement conformance suite mirroring tests/conformance/six-sti/. */
class ${PASCAL}BasicLifecycleTest {

    @Test
    void portMetadataIsConsistent() {
        ${PASCAL}VenueAdapter adapter = new ${PASCAL}VenueAdapter();
        assertThat(adapter.venueMic()).isNotNull();
        assertThat(adapter.tier()).isIn(LatencyTier.HOT, LatencyTier.WARM, LatencyTier.COLD);

        HealthSnapshot snap = adapter.health();
        assertThat(snap.venueId()).isEqualTo(adapter.venueMic());
    }
}
EOF

# Find next free ADR number
ADR_DIR="docs/decisions"
NEXT=$(ls "${ADR_DIR}" 2>/dev/null | sed -nE 's/^([0-9]{4})-.*/\1/p' | sort -n | tail -1)
NEXT=$((10#${NEXT:-0} + 1))
ADR_NUM=$(printf '%04d' $NEXT)
ADR_FILE="${ADR_DIR}/${ADR_NUM}-venue-adapter-${LOWER}.md"

cat > "${ADR_FILE}" <<EOF
---
status: proposed
date: $(date -u +%Y-%m-%d)
deciders: TBD
---

# ADR ${ADR_NUM}: Onboard ${PASCAL} as a new venue adapter

## Context and Problem Statement

We need to connect to ${PASCAL}. As per Constitution Principle I, this is
an additive change — only the new adapter module is created; the domain,
OMS, EMS, reconciler, reporting and surveillance services stay
untouched.

## Decision

Implement ${DIR}/ as a new ${PASCAL}VenueAdapter implementing
\`VenueGatewayPort\`. Latency tier: \`WARM\` by default; revisit if the
venue exposes a co-location option.

## Implementation checklist

- [ ] MIC chosen (4 chars, ISO 10383)
- [ ] Protocol selected (FIX 4.4 / FIX 5.0 SP2 / proprietary binary / vendor SDK)
- [ ] Conformance test suite (mirror tests/conformance/six-sti/)
- [ ] Drop-copy stream wired to \`warm.dropcopy.${LOWER}.v1\` (Constitution V)
- [ ] Helm chart in ${DIR}/helm/
- [ ] Tilt extension in tools/tilt/extensions/venue_adapter_${LOWER}.star
- [ ] CODEOWNERS entry for ${DIR}/
EOF

# Add to settings.gradle.kts
SETTINGS="settings.gradle.kts"
if ! grep -q "apps:venue-adapter-${LOWER}" "${SETTINGS}"; then
  cat >> "${SETTINGS}" <<EOF

// Generated by scripts/new-venue.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
include("apps:venue-adapter-${LOWER}")
EOF
fi

echo "✓ Scaffolded ${DIR}"
echo "✓ Wrote ${ADR_FILE}"
echo "✓ Updated ${SETTINGS}"
echo ""
echo "Next steps:"
echo "  1. fill in the TODOs in ${PASCAL}VenueAdapter"
echo "  2. add a conformance test that exercises NEW → PARTIAL_FILL → FILL"
echo "  3. extend tools/tilt/extensions/ with a venue_adapter_${LOWER}.star"
